"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/common/Footer";
import Navbar from "./components/common/Navbar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [shownav, setshownav] = useState(false);

  const handlenav = (e) => {
    console.log("This function is clicked", e);
    setshownav(e);
  };

  return (
    <html lang="en">
      <body className={` ${inter.className}`}>
        <Navbar shownav={shownav} setshow={handlenav} />
        <div className={`${shownav ? "blur-sm lg:blur-0" : "blur-0"}`}>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
